# Generated by Django 4.2.13 on 2026-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='location_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='location_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
