# Generated by Django 4.2.13 on 2026-03-04 08:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('liens', models.CharField(default='None', max_length=100)),
                ('liens_status', models.CharField(choices=[('clean', 'Clean'), ('issue', 'Issue Found')], default='clean', max_length=20)),
                ('restrictions', models.CharField(default='None', max_length=100)),
                ('restrictions_status', models.CharField(choices=[('clean', 'Clean'), ('issue', 'Issue Found')], default='clean', max_length=20)),
                ('theft_records', models.CharField(default='Not reported', max_length=100)),
                ('theft_status', models.CharField(choices=[('clean', 'Clean'), ('issue', 'Issue Found')], default='clean', max_length=20)),
                ('registration', models.CharField(default='Active', max_length=100)),
                ('registration_status', models.CharField(choices=[('clean', 'Clean'), ('issue', 'Issue Found')], default='clean', max_length=20)),
            ],
            options={
                'verbose_name': 'Legal Status',
                'verbose_name_plural': 'Legal Statuses',
                'ordering': ['-id'],
            },
        ),
    ]
