# Generated by Django 4.2.13 on 2026-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalstatus',
            name='liens_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='liens_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='registration_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='registration_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='restrictions_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='restrictions_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='theft_records_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalstatus',
            name='theft_records_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
