volumes:
  autochecker_local_postgres_data: {}
  autochecker_local_postgres_data_backups: {}
  autochecker_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: autochecker_local_django
    container_name: autochecker_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '${DJANGO_PORT:-8000}:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: autochecker_local_postgres
    container_name: autochecker_local_postgres
    volumes:
      - autochecker_local_postgres_data:/var/lib/postgresql/data
      - autochecker_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: autochecker_local_redis
    volumes:
      - autochecker_local_redis_data:/data

  celeryworker:
    <<: *django
    image: autochecker_local_celeryworker
    container_name: autochecker_local_celeryworker
    depends_on:
      - redis
      - postgres
      - django
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: autochecker_local_celerybeat
    container_name: autochecker_local_celerybeat
    depends_on:
      - redis
      - postgres
      - django
    ports: []
    command: /start-celerybeat
