# Generated by Django 4.2.13 on 2026-03-04 08:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MileageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('mileage_km', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Mileage Record',
                'verbose_name_plural': 'Mileage Records',
                'ordering': ['date'],
            },
        ),
    ]
