# Generated by Django 4.2.13 on 2026-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileagerecord',
            name='source_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mileagerecord',
            name='source_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
