# Generated by Django 4.2.13 on 2026-03-04 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major')], default='minor', max_length=20)),
                ('damage_area', models.CharField(max_length=200)),
                ('damage_description', models.TextField(blank=True)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accident_type', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('impact_zone', models.CharField(blank=True, max_length=100)),
                ('airbags_deployed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Accident',
                'verbose_name_plural': 'Accidents',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AccidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='accidents/photos/')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Accident Photo',
                'verbose_name_plural': 'Accident Photos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('claim_status', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=200)),
                ('claim_number', models.CharField(max_length=100)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim', to='accidents.accident')),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-id'],
            },
        ),
    ]
