# Generated by Django 4.2.13 on 2026-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='accident_type_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accident',
            name='accident_type_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accident',
            name='damage_area_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accident',
            name='damage_area_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accident',
            name='damage_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accident',
            name='damage_areas_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accident',
            name='damage_areas_ru',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accident',
            name='damage_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='damage_description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accident',
            name='impact_zone_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accident',
            name='impact_zone_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accident',
            name='location_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='accident',
            name='location_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='accident',
            name='police_report_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='accident',
            name='repair_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accident',
            name='repair_status_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accident',
            name='repair_status_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='claim_status_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='claim_status_ru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='provider_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='provider_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
