# Generated by Django 4.2.13 on 2026-03-04 08:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accidents_count', models.IntegerField(default=0)),
                ('accidents_status', models.CharField(choices=[('clean', 'Clean'), ('issues_found', 'Issues Found'), ('warning', 'Warning')], default='clean', max_length=20)),
                ('mileage_status', models.CharField(choices=[('clean', 'Clean'), ('issues_found', 'Issues Found'), ('warning', 'Warning')], default='clean', max_length=20)),
                ('legal_status', models.CharField(choices=[('clean', 'Clean'), ('issues_found', 'Issues Found'), ('warning', 'Warning')], default='clean', max_length=20)),
                ('service_records_count', models.IntegerField(default=0)),
                ('taxi_usage', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehicle Check',
                'verbose_name_plural': 'Vehicle Checks',
                'ordering': ['-id'],
            },
        ),
    ]
